# Generated by Django 5.0.6 on 2024-06-30 23:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('marca', models.CharField(default='Sin Marca', max_length=30)),
                ('precio_oferta', models.IntegerField(blank=True, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_envio', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(max_length=13, verbose_name='RUT de la Empresa')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la Empresa')),
                ('representante_legal', models.CharField(default='', max_length=100, verbose_name='Representante Legal')),
                ('contacto_empresa', models.CharField(max_length=50, verbose_name='Contacto de la Empresa')),
                ('direccion_proveedor', models.CharField(default='sin direccion', max_length=255, verbose_name='Dirección')),
                ('email_proveedor', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tfno', models.CharField(max_length=8, verbose_name='Telefono')),
                ('clave', models.CharField(max_length=30)),
                ('confirmar_clave', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Bodeguero'), ('CLIENT', 'Cliente')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('agregado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('foto_producto', models.ImageField(upload_to='productos_proveedor/', verbose_name='Foto del Producto')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Costo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='menu.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_orden_compra', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorCarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('en_resumen', models.BooleanField(default=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.proveedorcarrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.productosproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_llegada', models.IntegerField(default=0)),
                ('fecha_agregado', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmado', models.BooleanField(default=False)),
                ('en_resumen', models.BooleanField(default=True)),
                ('precio_venta', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio de venta')),
                ('marca', models.CharField(default='Sin Marca', max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(default='en_resumen', max_length=20)),
                ('carrito_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='menu.proveedorcarritoitem')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_boleta', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.articulos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlativo', models.IntegerField(editable=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.articulos', verbose_name='Articulos')),
                ('id_orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='menu.compra')),
            ],
            options={
                'unique_together': {('id_orden_compra', 'correlativo')},
            },
        ),
    ]
