# Generated by Django 5.0.6 on 2024-06-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
