# Generated by Django 5.0.4 on 2024-07-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_recepcionproducto_precio_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecepcionProducto',
        ),
    ]
