# Generated by Django 5.0.4 on 2024-07-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_delete_recepcionproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProveedorCarritoItem',
        ),
    ]
