# Generated by Django 5.0.4 on 2024-07-01 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_proveedorcarritoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedorcarrito',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ProductosProveedor',
        ),
        migrations.DeleteModel(
            name='ProveedorCarrito',
        ),
    ]
