# Generated by Django 5.0.4 on 2024-07-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_delete_detallecompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
