# Generated by Django 5.0.4 on 2024-07-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_delete_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
