# Generated by Django 5.0.4 on 2024-07-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('stock_actual', models.IntegerField(blank=True, null=True, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(blank=True, null=True, verbose_name='Stock Mínimo')),
                ('precio_costo', models.IntegerField(verbose_name='Precio de Costo')),
                ('precio_venta', models.IntegerField(default=0, verbose_name='Precio de Venta')),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Foto del Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
