# Generated by Django 5.0.4 on 2024-07-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('correlativo', models.IntegerField(verbose_name='Número Correlativo')),
                ('cantidad', models.IntegerField()),
                ('precio_costo', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='menu.compra', verbose_name='Orden de Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.producto', verbose_name='Producto')),
            ],
        ),
    ]
