# Generated by Django 5.0.4 on 2024-07-01 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_detallecompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
