# Generated by Django 5.0.4 on 2024-07-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_detallecompra_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEnHome',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='menu.producto')),
            ],
        ),
    ]
