# Generated by Django 5.0.4 on 2024-07-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_productoenhome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoEnHome',
        ),
    ]
