# Generated by Django 5.0.4 on 2024-07-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mostrar_en_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en Home'),
        ),
    ]
