# Generated by Django 5.0.6 on 2024-07-03 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_producto_mostrar_en_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='articulo',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.producto'),
            preserve_default=False,
        ),
    ]
