# Generated by Django 5.0.4 on 2024-07-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_publicidad_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicidad',
            name='segundos',
        ),
    ]
