# Generated by Django 5.0.4 on 2024-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_remove_publicidad_segundos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidades/')),
                ('tiempo', models.IntegerField(choices=[(1, '1 Semana'), (2, '2 Semanas'), (4, '1 Mes'), (12, '3 Meses')])),
                ('segundos', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
