# Generated by Django 5.0.4 on 2024-07-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_solicitudpublicidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpublicidad',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpublicidad',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
