# Generated by Django 5.0.4 on 2024-07-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_solicitudpublicidad_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpublicidad',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
