# Generated by Django 5.0.4 on 2024-07-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_solicitudpublicidad_publicada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpublicidad',
            name='fecha_publicacion',
        ),
    ]
