# Generated by Django 5.0.6 on 2024-07-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0026_remove_solicitudpublicidad_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion_retiro',
            field=models.CharField(default='Piedra Roja 125, Quilicura, Chile', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entregado', 'Entregado')], default='Pendiente', max_length=10),
        ),
    ]
