# Generated by Django 5.0.4 on 2024-07-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0027_venta_direccion_retiro_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='cantidad_llegada',
            field=models.IntegerField(default=0, verbose_name='Cantidad Llegada'),
        ),
    ]
